name: Generate Data Index

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "data/restitutions/etablissements/**"
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Debug git state
        run: |
          git pull
          git status
          git branch -a

      #- name: Setup Node
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: 20

      - name: Generate index
        run: node scripts/generate-index.js

      - name: Commit index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data-index.json"
          file_pattern: data-index.json
