name: Generate Data Index

on:
  push:
    paths:
      - "data/restitutions/etablissements/**"
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate index
        run: node scripts/generate-index.js

      - name: Commit index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data-index.json"
          file_pattern: data-index.json
